### ISSUE TITLE
default behavior of clang-format should be identical to command line

### ISSUE THREAD

**Issue by krux02** [Chiel92/vim-autoformat#95] opened 2015-11-13 03:16 UTC
When I use this plugin without config on a project that has a `_clang-format` file, it should use this. This is also the default behavior on the command line, when I use clang-format without any argument on the shell.

Yes, a fallback configuration, when no file was found, should be possible to choose, but I do not think that a configuration hard coded into the plugin should overshadow by default an available `_clang-format` file.

**Comment by Congee** [comment] 2015-11-13 06:54
Agree

**Comment by Chiel92** [comment] 2015-11-27 12:53
Sounds plausible. I'm not a clang user. What would be your suggested default argument list?

**Comment by krux02** [comment] 2015-11-27 13:45
I would replace the style parameters with these: `-style=file -fallback-style=llvm`. It basically means, it should look for a format style file in the folder of the source file and it's parents, if it's found it should use it, otherwise it should use the built in style llvm. The fallback style can actually also be any of the other build in style, I think their are good arguments for all of them, but only one of them can be chosen. The `--assume-filename=<string>` parameter needs to have the full file path, otherwise clang format can't find the style file, currently it has only the buffer name, which is OK to detect the file type, but not enough for the `-style=file` parameter.

**Comment by Chiel92** [comment] 2015-11-27 15:23
Am I correct that the `-fallback-style` parameter cannot take a string like `{BasedOnStyle: WebKit, AlignTrailingComments: true'}` as value?
That would be a bummer, as it would break the integration with vim options like `shiftwidth` etcetera.

**Comment by krux02** [comment] 2015-11-27 17:54
I tested it, and it seems like you are right, `-fallback-style` only supports built in styles.

So at the moment I see two options:

    1. Reimplement the search for _clang-format file. And have two distinct calls, one where the _clang-format file was found, and the one, where it wasn't. This shouldn't be hard to implement, but it would break the simplicity to configure the plugin, because now there are two different configurations for the same tool. But on the other hard, the search could be extended, to also include a path to the `/.vim/ folder, so that  everybody can have the full power of a _clang-format file to define the fallback.

    2. Ask the clang format people to pimp the fallback style parameter as a feature request. The people from clang-format are all smart people, and I think with the right arguments, they are willing to support this option, because I can't imagine that this is complicated or time consuming to implement.

**Comment by Chiel92** [comment] 2015-12-03 16:07
Regarding 2, I asked a question on the cfe-dev mailing list with no response thus far.
Besides that, other formatters too (https://github.com/Chiel92/vim-autoformat/pull/99) seem to need the functionality from 1, so we might as well adopt this approach.

I will see if have time this weekend to get my hands on it.

**Comment by Chiel92** [comment] 2015-12-04 09:02
@krux02  I pushed a proposal to branch `dev`. Could you check it out and verify if it works for you?

**Comment by svenstaro** [comment] 2016-02-02 04:29
So what's the status here? Which is the commit to be tested?

**Comment by Chiel92** [comment] 2016-02-02 16:59
Its about https://github.com/Chiel92/vim-autoformat/commit/d704fd1647d6e42c4cfd6d3161e940801da71236

**Comment by Chiel92** [comment] 2016-02-06 08:49
I decide to push the current implementation to master. I will leave this issue open until it has been confirmed to work with clang 3.7.

**Comment by Chiel92** [comment] 2016-02-06 08:59
@svenstaro can already say something about whether it works for you?

**Comment by Chiel92** [comment] 2016-02-29 09:29
Apparently the `--assume-filename` argument should be a full path to make finding the rc file work correctly, in case the edited file is not in the current working directory.
[This pull request](https://github.com/Chiel92/vim-autoformat/pull/117) fixes this. Can someone confirm this issue is solved?

**Comment by Chiel92** [comment] 2016-03-11 17:12
Assuming this issue is solved, closing.

**Closed by Chiel92** 2016-03-11 17:12 UTC

**Comment by Paschalis** [comment] 2017-02-06 12:55
Actually I am having some issues with this. I am not sure whether is my fault or not, but `clang-format` produces the correct output and `Autoformat` does not.
I am not talking about project specirfic ".clang-format" file, but for the default one on home directory.
The behavior in both scenarios should be the same though w/ `clang-format` binary.

What I do, is I set my vim configuration to "4 spaces":
```
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4 
set autoindent
set smartindent
```

My `~/.clang-format` is:
```
---
BasedOnStyle: Google
IndentWidth: 2
```

`Autoformat` still indents with 4 spaces. I would expect it however to overwrite vim`s settings, and perform a 2 space indentation.

BTW, there are two options in the changelog that relate to this issue. [This](
https://github.com/Chiel92/vim-autoformat#march-13-2013) and [this](https://github.com/Chiel92/vim-autoformat#march-16-2013)

Am I doing something wrong here?
Or should I set explicitly in my vimrc something like:
for c family languages: overwrite vims above settings.

If so, what is this option?

PS thats for the nice plugin!

**Comment by Chiel92** [comment] 2017-02-06 13:40
> Autoformat still indents with 4 spaces. I would expect it however to overwrite vim`s settings, and perform a 2 space indentation.

I disagree with this, because you want the vim options to have correct values. This affects vim's indent behaviour and what not. So you should indeed set those options in your vimrc. Clang-format will then use these settings through vim-autoformat. If you only want those options in a single directory or something, e.g. because you work on projects with different formatting styles, have a look at
http://editorconfig.org/

**Comment by Paschalis** [comment] 2017-02-06 14:41
Hi @Chiel92 ,  I've deleted my post, as I found the root cause of this problem.
So my `.clang-format` was setting the `indent` value, and both `Autoformat` and `clang-format` respected it. The issue I was having was due to a different fact,  described in a new `Issue`.
Cheers!

**Comment by svenstaro** [comment] 2017-05-29 07:43
The original issue does not actually seem solved for me.
