### ISSUE TITLE
autopep8 does nothing

### ISSUE THREAD

**Issue by wolframm** [Chiel92/vim-autoformat#62] opened 2015-07-10 21:10 UTC
I installed autopep8 on my Ubuntu 15.04 system and verified that it works on the command line using "autopep8 -i -a somefile.py". Autopep8 is available globally.

Then I installed vim-autoformat using vundle. PluginList shows it is installed. When running :Autoformat, absolutely nothing happens. For example, I wish to have whitespaces (__) removed from the following code snippet:

for ___item in somelist: print item

When running autopep from the command line, the code is reformatted to:

for item in somelist: print item

When running :Autoformat, nothing happens.

I tried changing the default for autopep8 in vim-autoformat/plugin/defaults.vim to include --aggressive. Again, nothing.

Please advise. No idea what's going on here.

Arne

**Comment by Chiel92** [comment] 2015-07-25 12:44
Could you please verify that you are on the latest commit in the master branch?

**Comment by icher** [comment] 2015-08-01 16:38
I confirm this. :Autoformat in .py files does nothing. In .cpp files works fine.

Ubuntu 15.04, Vi IMproved 7.4,  autopep8 0.9.1.

~/.vim/bundle/vim-autoformat $ git pull                  
Already up-to-date.

**Comment by Chiel92** [comment] 2015-08-02 18:35
I have version 1.0.3. Don't know if that makes a difference.
What does the line 
```bash
$ cat foo.py | autopep8 - 
```
do for you?

**Comment by Chiel92** [comment] 2015-08-31 19:06
Closing until further information is provided.

**Closed by Chiel92** 2015-08-31 19:06 UTC

**Comment by mal-w** [comment] 2020-02-01 17:37
I think the issue is that autopep8 doesn't really do much with just `autope8 -`
add the --aggressive argument to wherever you set up your keymap in the vimrc.

If you followed this from the help page:
```
let g:formatdef_autopep8 = "'autopep8 - --range '.a:firstline.' '.a:lastline"
let g:formatters_python = ['autopep8']
```

Then change it to 
```
let g:formatdef_autopep8 = "'autopep8 - --aggressive --range '.a:firstline.' '.a:lastline"
let g:formatters_python = ['autopep8']
```
