### ISSUE TITLE
Autoformat deletes last line

### ISSUE THREAD

**Issue by przemekd** [Chiel92/vim-autoformat#74] opened 2015-10-06 13:59 UTC
To reproduce the issue create Exemple.rb file in vim:
```
class Example
  def dummy
    nil
  end
end
```
When one use autoformat the last line is deleted. The command ruby-beautify doesn't remove it when it is executed through command line..

ruby-beautify -v
0.97.3

ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by przemekd** [comment] 2015-10-06 14:41
Ok, it looks like it is the ruby-beautify issue [Issue](https://github.com/erniebrodeur/ruby-beautify/issues/23). Sorry to bother you!

**Comment by Chiel92** [comment] 2015-10-06 16:51
No problem! Glad you solved it.

**Comment by kuon** [comment] 2015-10-29 13:36
I had the same issue, it doesn't seem to be the ruby-beautify issue as running outside of vim-autoformat doesn't eat the last line.

I worked around it with:

`noremap <F1> Go<ESC>:Autoformat<CR>`

in my : `ftplugin/ruby.vim`

**Comment by Chiel92** [comment] 2015-10-29 17:34
Strange. Vim-autoformat should only remove the lastline if its empty.

@kuon you could comment out the  code in autoformat.vim that removes the last newline.
I.e. the part 

```vim
    if stdoutdata[-1] == os.linesep:
        stdoutdata = stdoutdata[:-1]
```

in the function `TryFormatterPython` and see if that makes a difference.
But I expect not and that the problem is somewhere deeper.

Could you post the version of ruby-beautify, your OS and some sample code that has the issue?

**Comment by kuon** [comment] 2015-10-30 16:46
Ok, I think I found the issue.

```text = os.linesep.join(vim.current.buffer[:])```

is the culprit, as it eats the last `\n`

I checked the file with hexdump, last char is a `\n` (`0x0a`) and if I add `print(hex(ord(text[-1])))` after the above line, it prints `0x64` which correspond to the `d` of the `end`.



I agree that rbeautify shouldn't eat the last line when not terminated by a `\n` but it would be a good thing for `vim-autoformat` to pass the buffer "as is".

**Comment by Chiel92** [comment] 2015-11-11 17:14
I would say though, that it wouldn't hurt to append a `\n` to the text before sending it to the formatter. Let me give it a try.

**Comment by Chiel92** [comment] 2015-11-11 17:23
I pushed this to branch `dev`. Would this solve your issue? @przemekd  @kuon

**Comment by kuon** [comment] 2015-11-12 10:22
Seems to fix the issue

**Comment by Chiel92** [comment] 2015-11-12 14:23
Merged into master.

**Closed by Chiel92** 2015-11-12 14:23 UTC

**Comment by hzulla** [comment] 2016-01-25 14:22
There was a minor bug in the beautify gem. It's fixed in https://github.com/erniebrodeur/ruby-beautify/pull/31

**Comment by Chiel92** [comment] 2016-01-25 16:14
Thanks!
