### ISSUE TITLE
autoformat can not use formatters

### ISSUE THREAD

**Issue by tuoppimas** [Chiel92/vim-autoformat#107] opened 2016-02-10 21:32 UTC
I am getting the following error when I run :Autoformat:

Definition in 'g:formatdef_clangformat' was unsuccessful.
Definition in 'g:formatdef_astyle_c' was unsuccessful.
No format definitions were successful.
Press ENTER or type command to continue

It does not work for any of the installed formatters . I can still cycle through the formatters with the next and previous commands, but it wont do the actual formatting.

**Comment by Chiel92** [comment] 2016-02-11 16:33
Have you installed either of the formatters? If yes, can you run them from the commandline? I.e. are they in your path?

**Comment by tuoppimas** [comment] 2016-02-11 22:19
Yes, 
I run linux mint and have installed clang-format and the html beautify through the apt-get package manager.
For example if i run:
    clang-format-3.6 test.c

It outputs test.c formatted properly. I have also tried different versions of clang-format and also removing and reinstalling the package.
Things broke when I updated my vim plugins. 

Thank you for your help.

Tuomas


________________________________________

**Comment by Chiel92** [comment] 2016-02-12 09:04
So, it has worked in the past for you? Have you any additional configuration in your vimrc related to vim-autoformat?

**Comment by tuoppimas** [comment] 2016-02-12 09:51
I use the:
let g:autoformat_autoindent = 0
but except for that I have no autoformat-related configurations.

I think that at some level it does recognize the formatters because I can cycle through them with the :nextformatter command and then view with the :currentformatter. The actual formatting does not work for any formatters - I get the same error:

Definition in X was unsuccessful.
No format definitions were successful.


How does the recognition of the formatters work? Maybe I should try setting them manually.

Tuomas

________________________________________

**Comment by Chiel92** [comment] 2016-02-12 11:28
You should have gotten more error message than those though, I think. When you have `:set verbose = 1`, vim-autoformat tries all formatters, and writes the stderr as error messages. Please be sure to post the entire output of `:messages`.

In the current implementation, which is likely to change in the near future, you can get the format command used from `echo &formatprg`. So to check things manually, execute the contents from `&formatprg` in command mode and inspect the output.

**Comment by tuoppimas** [comment] 2016-02-12 18:18
Hi,
I did some more testing with the &formatprg. 
For html it gives html-beautify -f - -s 4    // this does not format a file from the command line
For C it gives astyle --mode=c --style=andi -pcHs4  // this works and formats a file from the command line
But neither work inside vim.
C:
Definition in 'g:formatdef_clangformat' was unsuccessful.
Definition in 'g:formatdef_astyle_c' was unsuccessful.
No format definitions were successful.
Press ENTER or type command to continue

HTML error:

Error detected while processing function <SNR>28_TryAllFormatters..<SNR>28_TryFormatterPython:
line   42:
Traceback (most recent call last):
  File "<string>", line 30, in <module>
IndexError: string index out of range
Definition in 'g:formatdef_htmlbeautify' was successful.



For python and autopep8 the formatting works fine.


Tuomas

________________________________________

**Comment by tuoppimas** [comment] 2016-02-12 18:44
I got it working for c also by editing the defaults.vim file.

I am still getting an error for html files:

Error detected while processing function <SNR>28_TryAllFormatters..<SNR>28_TryFormatterPython:
line   42:
Traceback (most recent call last):
  File "<string>", line 30, in <module>
IndexError: string index out of range
Definition in 'g:formatdef_htmlbeautify' was successful.

What does this mean?



________________________________________

**Comment by Chiel92** [comment] 2016-02-15 08:54
That IndexError looks like a bug. I pushed a fix to master. Could you check it out and see if that changes the output?

**Comment by tuoppimas** [comment] 2016-02-15 10:57
Hi,
now it says the formatdefinition for htmlbeautify was successful, but all the contents of the buffer are lost when I run it.
I can use another plugin to format my HTML code with the same formatter.

Tuomass
 
________________________________________

**Comment by Chiel92** [comment] 2016-02-15 12:07
Very peculiar. So let's dive into this ;).
What python version are you running in Vim? (`:py import sys;print(sys.version)`)
What is your vim version?
Do you run terminal vim or gvim?

What happens if you execute the commandline string from `&formatprg` manually inside vim?
I.e. `:! astyle --mode=c --style=ansi -pcHs4`?

**Comment by tuoppimas** [comment] 2016-02-15 13:26
Hi,


I am running vim in terminal, I use linux mint 17.3 and the "terminator" terminal emulator.

py import sys;print(sys.version) gives me:

2.7.6 (default, Jun 22 2015, 18:01:27)
[GCC 4.8.2]

and the manual format command:

Cannot process the input stream

Artistic Style has terminated

shell returned 1

Press ENTER or type command to continue


But when I run it from terminal with an input file, it succeeds:
Formatted  /home/tuomas/t-106-5300/simpleled.c


Tuomas



________________________________________

**Comment by Chiel92** [comment] 2016-02-15 16:54
> Cannot process the input stream
> Artistic Style has terminated
> shell returned 1

My bad, I made a typo.
The command should be `:%!astyle --mode=c --style=ansi -pcHs4`

**Comment by tuoppimas** [comment] 2016-02-16 09:05
This command formats my code correctly.

Tuomas

________________________________

**Comment by Chiel92** [comment] 2016-02-16 12:35
Well, that is annoying. That means the problem really occurs in the vim-autoformat code. Can you confirm you are on the latest master branch? Moreover, are you able to find a commit for which it still works for you?

**Comment by jamesla** [comment] 2016-02-18 05:29
I'm also getting this error and I haven't really changed anything recently other than a plugin update

**Comment by Chiel92** [comment] 2016-02-22 15:52
I have tried reproducing the issue on both my windows and linux machine using astyle and html-beautify, but without success. Since I can't fix an issue I'm unable to reproduce, I will leave this issue be until more details are specified and/or a reproduction scenario is known.

**Comment by tuoppimas** [comment] 2016-02-22 22:13
For now I am using another vim plugin to format my HTML code. This works for python, C and C++.

**Comment by tuoppimas** [comment] 2016-02-25 10:41
I have fixed the issue by deleting my /bundle/vim-autoformat folder and all of it's contents. Then I installed the plugin with Vundle :PluginInstall.
I also had to edit the defaults.vim line - I changed the format commant "clang-format" to "clang-format-3.6". This could also maybe fixed by making an alias.
________________________________________

**Comment by Chiel92** [comment] 2016-03-11 17:31
> I have fixed the issue by deleting my /bundle/vim-autoformat folder and all of it's contents. Then I installed the plugin with Vundle :PluginInstall.

Did this also fix it for html-beautify?

> I also had to edit the defaults.vim line - I changed the format commant "clang-format" to "clang-format-3.6". This could also maybe fixed by making an alias.

Yes, it could. You can also just put it in your vimrc.
But actually, I find it weird that you can't call `clang-format`, only `clang-format-3.6.`
On my systems they exist either both or just `clang-format`.

**Comment by Chiel92** [comment] 2016-04-28 09:24
Closing. When similar problems arise, please create a new issue.

**Closed by Chiel92** 2016-04-28 09:24 UTC
