### ISSUE TITLE
formatting jumps to top of the page

### ISSUE THREAD

**Issue by ericlagergren** [Chiel92/vim-autoformat#215] opened 2017-10-26 04:15 UTC
Basically:  if I make an edit, save the file, then want to undo that edit, I have to press `u` twice because the first press simply jumps me back to the top of the page.

Using vim version: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  5 2017 19:19:02)`

On commit: f68c2cc9b61728e4019bc2ce9a481c91b5d2de79

From: https://github.com/Chiel92/vim-autoformat/issues/56#issuecomment-337235379

**Comment by Chiel92** [comment] 2017-10-31 12:03
So the formatting doesn't actually jump to the top, but undoing does?

**Comment by ericlagergren** [comment] 2017-10-31 17:37
correct, yeah. formatting stays where it is but the undo button is messed up.

**Comment by Chiel92** [comment] 2017-11-08 09:35
This behaviour has always been in vim-autoformat, and I'm not sure yet how to fix it.

**Comment by dc3671** [comment] 2017-11-08 16:04
@ericlagergren I think the mechanism of `vim-autoformat` is generating a temp file with linter and replace the original file's all content with it. So in undo's vision, you replace all the file content with another, and this operation leads to jumping to the top. That's my thought of explanation to your problem.

So it's basically a mechanical problem, not a bug.

**Comment by Chiel92** [comment] 2017-11-08 17:29
@dc3671 in case of eslint (and few others) you are correct about the temp file, but for the vast majority of the formatter vim-autoformat read from the stdin.

Still, that means replacing the entire buffer contents nonetheless.

**Comment by Chiel92** [comment] 2018-10-16 15:16
Duplicate of https://github.com/Chiel92/vim-autoformat/issues/131

**Closed by Chiel92** 2018-10-16 15:16 UTC
