### ISSUE TITLE
Error when autoformatting html file

### ISSUE THREAD

**Issue by pigeon1990** [Chiel92/vim-autoformat#259] opened 2018-12-10 03:08 UTC
```
Trying definition from g:formatdef_htmlbeautify
Evaluated formatprg: html-beautify -f - -t
Using python 2 code...
Formatter htmlbeautify has errors: Unable to open path "/Users/jeff/Downloads/-"
Run `html-beautify -h` for help.
Definition in 'g:formatdef_htmlbeautify' was unsuccessful.
Trying definition from g:formatdef_tidy_html
Evaluated formatprg: tidy -q --show-errors 0 --show-warnings 0 --force-output --indent auto --indent-spaces 8 --vertical-space yes --tidy-mark no -wrap 0
Using python 2 code...
Formatter tidy_html gives nonzero returncode: 2
Definition in 'g:formatdef_tidy_html' was successful.
```

**Comment by Chiel92** [comment] 2018-12-10 09:14
Thanks for reporting your issue. This might well be due to a code flow issue in the python 2 version. I just pushed a fix. Could you please check if your issue is solved?

**Comment by Chiel92** [comment] 2018-12-13 09:09
Yes, so at least that is better than before. Question remains: why does tidy give returncode 2?
What happens if you run that command from the commandline yourself?

**Comment by Chiel92** [comment] 2018-12-13 12:02
This means that the issue is not with the vim-autoformat code. But let's dig a little further.
You can remove the `--show-errors 0` and the like, to see what it is that goes wrong.

**Comment by Chiel92** [comment] 2018-12-14 10:40
Ok, so that could be either due to version difference, or the default definition for tidy in vim-autoformat is just broken. Could you report your tidy version, and maybe retry the the above command without the `--force-output` argument?

**Comment by pigeon1990** [comment] 2018-12-20 06:56
1.tidy -version ```HTML Tidy for Mac OS X released on 31 October 2006 - Apple Inc. build 16.1```


2.without the --force-output argument ```tidy -q --show-warnings 0 --indent auto --indent-spaces 8 --vertical-space yes --tidy-mark no -wrap 0 a.html  ```
```html <!DOCTYPE html>

<html lang="en">
<head>
        <meta charset="UTF-8">

        <title>
        </title>
</head>

<body>
</body>
</html>
```
``` echo $? ``` output 1

**Comment by Chiel92** [comment] 2018-12-20 12:46
That sounds like a very old version. Could you install a newer one and see what happens? I suspect your version doesn't have support for the `--force-output` option.

**Comment by pigeon1990** [comment] 2018-12-21 07:15
```
➜  ~ tidy -q --show-warnings 0 --force-output --indent auto --indent-spaces 8 --vertical-space yes --tidy-mark no -wrap 0 a.html   
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <title>
        </title>
</head>
<body>
</body>
</html>
➜  ~ echo $?                                                                                                                                                    
0
➜  ~ tidy -version
HTML Tidy for Apple macOS version 5.6.0                                                                                                                                                
```

**Comment by pigeon1990** [comment] 2018-12-21 07:16
```
Trying definition from g:formatdef_htmlbeautify
Evaluated formatprg: html-beautify -f - -t
Using python 2 code...
Formatter htmlbeautify has errors: Unable to open path "/Users/liubaoji/-"
Run `html-beautify -h` for help.
Definition in 'g:formatdef_htmlbeautify' was unsuccessful.
Trying definition from g:formatdef_tidy_html
Evaluated formatprg: tidy -q --show-errors 0 --show-warnings 0 --force-output --indent auto --indent-spaces 8 --vertical-space yes --tidy-mark no -wrap 0
Using python 2 code...
Definition in 'g:formatdef_tidy_html' was successful.
```

**Comment by Chiel92** [comment] 2018-12-21 08:52
So, looks like that's solved. By the way, if you want to use `html-beautify` instead, which you seem to have installed, make sure to update to the latest version of vim-autoformat, because there has been a fix for that a few days ago.

**Closed by Chiel92** 2018-12-21 08:52 UTC

**Comment by pigeon1990** [comment] 2018-12-21 09:17
Thanks a million.
