### ISSUE TITLE
AStyle can't use the unix lineend

### ISSUE THREAD

**Issue by IceNature** [Chiel92/vim-autoformat#71] opened 2015-08-26 11:57 UTC
I added this in my `_vimrc`:

    let g:formatdef_astyle_cpp = '"astyle --mode=c -z2 --style=ansi -pcH".(&expandtab ? "s".&shiftwidth : "t")'

But every times I run `:Autoformat`,the C++ file will be changed to dos lineend.
AStyle 2.051 built by VS2013 .When I run it in cmd with `-z2`,it works will.

**Comment by Chiel92** [comment] 2015-08-26 14:06
In vim, what does the command `:echo &ff` say?

**Comment by IceNature** [comment] 2015-08-27 01:44
unix
But I see `^M` at the end of each line

**Comment by Chiel92** [comment] 2015-08-31 19:15
I can't reproduce this, as I'm a linux user. (I assume you work on windows, correct?)
One more question, do you use python2 or python3 with vim?

Anyway, I pushed a commit that uses `os.linesep` in the python code, instead of `'\n'`.
It can be found on the branch `newlines`.
Could you please check it out and tell if it makes a difference?

**Comment by IceNature** [comment] 2015-09-02 13:26
Yes I work on Windows and I have compiled Vim to support both py2 and py3.
But I am sorry that I may not be able to use computer recently so I can't test this now. I have forked it and will test it as soon as I could.
If needed,I will close this issue and reopen it after I test.

**Comment by IceNature** [comment] 2015-09-17 14:21
I have tested the "newlines" branch and it worked as I wanted. Thank you for your help.

**Comment by Chiel92** [comment] 2015-09-22 08:21
I pushed this fix to the master branch. Thank you for reporting this.

One more question, can you confirm this works for both python2 and python3?

**Comment by IceNature** [comment] 2015-09-22 13:18
Aha, it gave me an error message:
>Error detect while processing function <SNR>14_TryAlllFormatter..<SNR>14_TryFormatterPython3:
>line 32:
>Traceback (most recent call last):
>     File "<string>", line 27, in <module>
>TypeError: Type str doesn't support the buffer API

Windows 7 x86, Python 3.4 x86

**Comment by IceNature** [comment] 2015-09-22 13:20
Aha, it gave me an error message:
Error detect while processing function <SNR>14_TryAlllFormatter..<SNR>14_TryFormatterPython3:
line 32:
Traceback (most recent call last):
     File "<string>", line 27, in <module>
TypeError: Type str doesn't support the buffer API
Windows 7 x86, Python 3.4 x86

**Comment by Chiel92** [comment] 2015-09-22 14:12
That's what I was afraid of. I will look into it.

**Comment by Chiel92** [comment] 2015-10-10 12:03
Closing as discussion is going on in #76.

**Closed by Chiel92** 2015-10-10 12:03 UTC
